### PR TITLE
fix(wait-card): use the red button as the back button on this page

### LINKED ISSUE #2: Add missing back button on NFC screen
Currently, it is impossible to go back from a screen where merchant needs to wait for card to be present. That is due to missing back button. 

Add back button, that will return the user to the screen where amount needs to be entered.

### PR DESCRIPTION
**Pull request by adrianboros**

### CODE REVIEW

File: src/pages/WaitCard.tsx [hunk 1]
```diff
@@ -86,15 +86,22 @@ export default function WaitCard({
...
+      // commenting out this for now.
+      //onCancel?.(); // Uncomment if we want to auto-cancel when NFC is not available
     }
   }, [autoFocus, handleTagFound, handleTagLost, onCancel]);
 
   useEffect(() => {
     const handleKeyDown = (e: KeyboardEvent) => {
-      if (e.key === "Backspace" || e.key === "ArrowLeft") {
+
+      if (
```
Comment (golobitch) [inline src/pages/WaitCard.tsx:99]: Normally, I would write this multiple ors like this:
```
if (["Backspace", "ArrowLeft", "SoftRight", "EndCall"].includes(e.key))
```
